root:
  # Choose the language you prefer to use on your server!
  # 
  # Currently Available:
  #  > en-US ( English )
  # 
  # If you do not see your language above, You can contribute by modifying the current en-US.yml
  # https://github.com/Crazy-Crew/BlockParticles/blob/main/paper/src/main/resources/locale/en-US.yml
  # Submit your finalized config using https://bin.bloom.host/ and send it to us in https://discord.gg/badbones-s-live-chat-182615261403283459
  # 
  language: en-US
  # Whether you want BlockParticles to shut up or not, This option is ignored by errors.
  verbose_logging: true
  # The command prefix you want shown in front of commands!
  command_prefix: '<dark_gray>[<dark_aqua>BlockParticles<dark_gray>]: '