settings:
  prefix: '&8[&aBP&8]: '
  heads:
    plants:
      #Tomato
      - '54482'
      #Mango
      - '46777'
      #Cherry
      - '67559'
      #Melon
      - '104643'
      #Mushroom
      - '105269'
      #Orange
      - '71401'
      #Golden Apple
      - '3333'